sudo: false
language: rust
rust:
- stable
- nightly

matrix:
  include:
    - rust: stable
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check

    - rust: nightly
      install:
      - rustup component add rustfmt

install:
- rustc -Vv
- cargo -V
- export PATH=$HOME/.cargo/bin:$PATH

script:
- cargo check --verbose
- cargo test  --verbose

branches:
  only:
  # Release tags
  - /^v\d+\.\d+\.\d+.*$/
  - master

cache:
  apt: true

notifications:
  email:
    on_success: never
